.TH OSC2FTDIDMX "1" "May 22, 2019"

.SH NAME
osc2ftdidmx \- an OSC to FTDI-DMX bridge

.SH SYNOPSIS
.B osc2ftdidmx
[\fIOPTIONS\fR] {\fURI\fR}*

.SH DESCRIPTION
\fBosc2ftdidmx\fP bridges OSC to an FTDI-based USB DMX adapter.

.SH OPTIONS
.HP
\fB\-v\fR
.IP
Print version and license information

.HP
\fB\-h\fR
.IP
Print usage information

.HP
\fB\-d\fR
.IP
Enable debug logging

.SH LICENSE
Artistic License 2.0.

.SH AUTHOR
Hanspeter Portner (dev@open-music-kontrollers.ch).
